const express = require("express");
const bcrypt = require("bcrypt");
const bodyParser = require("body-parser"); // convert input to readable string in req.body
const cookieSession = require("cookie-session");
const {
  generateRandomString,
  getUserByEmail,
  urlsForUser,
} = require("./helpers");

const app = express();
app.use(bodyParser.urlencoded({ extended: true }));
app.use(
  cookieSession({
    name: "session",
    keys: ["key1", "key2"],
  })
);
app.set("view engine", "ejs");

const PORT = 8080;
const urlDatabase = {}; // b6UTxQ: { longURL: "http://www.tsn.ca", userID: "aJ48lW" },
const users = {}; // userRandomID: { id: "userRandomID",email: "user@example.com", password: "hashed-password", },
const LENGTH = 6; // length of the random string to be generated by generateRandomString()

// GET

// list the URLs of the user
app.get("/urls", (req, res) => {
  if (req.session.userID) {
    const templateVars = {
      urls: urlsForUser(req.session.userID, urlDatabase),
      user: users[req.session.userID],
    };
    res.render("urls_index", templateVars);
  } else {
    res.redirect("/login");
  }
});

// form for creating a new URL
app.get("/urls/new", (req, res) => {
  if (req.session.userID) {
    const templateVars = {
      user: users[req.session.userID],
    };
    res.render("urls_new", templateVars);
  } else {
    res.redirect("/login");
  }
});

// details about a specific URL
app.get("/urls/:shortURL", (req, res) => {
  if (
    req.session.userID &&
    req.params.shortURL in urlDatabase &&
    req.session.userID === urlDatabase[req.params.shortURL].userID
  ) {
    const templateVars = {
      shortURL: req.params.shortURL,
      longURL: urlDatabase[req.params.shortURL].longURL,
      user: users[req.session.userID],
    };
    res.render("urls_show", templateVars);
  } else if (!req.session.userID) {
    res.redirect("/login");
  } else if (!(req.params.shortURL in urlDatabase)) {
    const templateVars = {
      user: users[req.session.userID],
      code: 404,
      message: "Page not found",
    };
    res.status(404).render("error", templateVars);
  } else {
    // req.session.userID !== urlDatabase[req.params.shortURL].userID)
    const templateVars = {
      user: users[req.session.userID],
      code: 403,
      message: "You are not authorized to access this resource.",
    };
    res.status(403).render("error", templateVars);
  }
});

// redirect /u/shortURL to the actual long URL
app.get("/u/:shortURL", (req, res) => {
  if (
    req.params.shortURL in urlDatabase &&
    urlDatabase[req.params.shortURL].longURL
  ) {
    res.redirect(urlDatabase[req.params.shortURL].longURL);
  } else {
    const templateVars = {
      user: users[req.session.userID],
      code: 404,
      message: "Page not found",
    };
    res.status(404).render("error", templateVars);
  }
});

// the register page
app.get("/register", (req, res) => {
  if (req.session.userID) {
    res.redirect("/urls");
  } else {
    res.render("register", { user: null });
  }
});

// the login page
app.get("/login", (req, res) => {
  if (req.session.userID) {
    res.redirect("/urls");
  } else {
    res.render("login", { user: null });
  }
});

// POST

// create new URL
app.post("/urls", (req, res) => {
  if (req.session.userID && req.body.longURL) {
    const shortURL = generateRandomString(LENGTH);
    urlDatabase[shortURL] = {
      longURL: req.body.longURL,
      userID: req.session.userID,
    };
    res.redirect(`/urls/${shortURL}`);
  } else if (!req.body.longURL) {
    const templateVars = {
      user: users[req.session.userID],
      code: 400,
      message: "You didn't submit a URL. Please try again.",
    };
    res.status(400).render("error", templateVars);
  } else {
    res.sendStatus(403);
  }
});

// update a URL
app.post("/urls/:shortURL", (req, res) => {
  if (
    req.session.userID &&
    req.params.shortURL in urlDatabase &&
    req.body.longURL &&
    req.session.userID === urlDatabase[req.params.shortURL].userID
  ) {
    urlDatabase[req.params.shortURL] = {
      longURL: req.body.longURL,
      userID: req.session.userID,
    };
    res.redirect("/urls");
  } else if (!req.body.longURL) {
    const templateVars = {
      user: users[req.session.userID],
      code: 400,
      message: "You didn't edit the URL. Please try again.",
    };
    res.status(400).render("error", templateVars);
  } else {
    res.sendStatus(403);
  }
});

// delete a URL
app.post("/urls/:shortURL/delete", (req, res) => {
  if (
    req.session.userID &&
    req.params.shortURL in urlDatabase &&
    req.session.userID === urlDatabase[req.params.shortURL].userID
  ) {
    delete urlDatabase[req.params.shortURL];
    res.redirect("/urls");
  } else {
    res.sendStatus(403);
  }
});

app.post("/register", (req, res) => {
  const existingUser = getUserByEmail(req.body.email, users);
  if (req.body.email && req.body.password && !existingUser) {
    const userID = generateRandomString(LENGTH);
    users[userID] = {
      id: userID,
      email: req.body.email,
      password: bcrypt.hashSync(req.body.password, 10),
    };
    req.session.userID = userID;
    res.redirect("/urls");
  } else if (existingUser) {
    const templateVars = {
      user: existingUser.id,
      code: 400,
      message: "This account already exists. Please login.",
    };
    res.status(400).render("error", templateVars);
  } else {
    const templateVars = {
      user: users[req.session.userID],
      code: 400,
      message: "Email or password are empty. Please try again.",
    };
    res.status(400).render("error", templateVars);
  }
});

app.post("/login", (req, res) => {
  const existingUser = getUserByEmail(req.body.email, users);
  if (
    existingUser &&
    req.body.password &&
    bcrypt.compareSync(req.body.password, existingUser.password)
  ) {
    req.session.userID = existingUser.id;
    res.redirect("/urls");
  } else {
    const templateVars = {
      user: users[req.session.userID],
      code: 403,
      message:
        "Email or password are incorrect. Please try again, or register if you don't have an account.",
    };
    res.status(403).render("error", templateVars);
  }
});

app.post("/logout", (req, res) => {
  req.session = null;
  res.redirect("/login");
});

// catch-all for non-existing pages
app.get("*", (req, res) => {
  const templateVars = {
    user: users[req.session.userID],
    code: 404,
    message: "Page not found",
  };
  res.render("error", templateVars);
});

app.listen(PORT, () => {
  console.log(`Example app listening on port ${PORT}!`);
});
